// Inicializa el mapa
const map = L.map('map').setView([20, 0], 2); // Coordenadas para centrar el mapa

// Capa base (Mapbox, OpenStreetMap, etc.)
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '© OpenStreetMap contributors'
}).addTo(map);

// Mapeo de nombres de países en español
const countryNamesInSpanish = {
    "AFG": "Afganistán",
    "ALB": "Albania",
    "DZA": "Argelia",
    "AND": "Andorra",
    "AGO": "Angola",
    "ARG": "Argentina",
    "ARM": "Armenia",
    "AUS": "Australia",
    "AUT": "Austria",
    "AZE": "Azerbaiyán",
    "BHS": "Bahamas",
    "BHR": "Baréin",
    "BGD": "Bangladés",
    "BRB": "Barbados",
    "BEL": "Bélgica",
    "BLZ": "Belice",
    "BEN": "Benín",
    "BTN": "Bután",
    "BOL": "Bolivia",
    "BIH": "Bosnia y Herzegovina",
    "BWA": "Botsuana",
    "BRA": "Brasil",
    "BRN": "Brunéi",
    "BGR": "Bulgaria",
    "BFA": "Burkina Faso",
    "BDI": "Burundi",
    "CPV": "Cabo Verde",
    "KHM": "Camboya",
    "CMR": "Camerún",
    "CAN": "Canadá",
    "CAF": "República Centroafricana",
    "TCD": "Chad",
    "CHL": "Chile",
    "CHN": "China",
    "COL": "Colombia",
    "COM": "Comoras",
    "COG": "República del Congo",
    "CRI": "Costa Rica",
    "CIV": "Costa de Marfil",
    "HRV": "Croacia",
    "CUB": "Cuba",
    "CYP": "Chipre",
    "CZE": "República Checa",
    "DNK": "Dinamarca",
    "DJI": "Yibuti",
    "DOM": "República Dominicana",
    "ECU": "Ecuador",
    "EGY": "Egipto",
    "SLV": "El Salvador",
    "GNQ": "Guinea Ecuatorial",
    "ERI": "Eritrea",
    "EST": "Estonia",
    "SWZ": "Esuatini",
    "ETH": "Etiopía",
    "FJI": "Fiyi",
    "FIN": "Finlandia",
    "FRA": "Francia",
    "GAB": "Gabón",
    "GMB": "Gambia",
    "GEO": "Georgia",
    "DEU": "Alemania",
    "GHA": "Ghana",
    "GRC": "Grecia",
    "GRD": "Granada",
    "GTM": "Guatemala",
    "GIN": "Guinea",
    "GNB": "Guinea-Bisáu",
    "GUY": "Guyana",
    "HTI": "Haití",
    "HND": "Honduras",
    "HUN": "Hungría",
    "ISL": "Islandia",
    "IND": "India",
    "IDN": "Indonesia",
    "IRN": "Irán",
    "IRQ": "Irak",
    "IRL": "Irlanda",
    "ISR": "Israel",
    "ITA": "Italia",
    "JAM": "Jamaica",
    "JPN": "Japón",
    "JOR": "Jordania",
    "KAZ": "Kazajistán",
    "KEN": "Kenia",
    "KIR": "Kiribati",
    "PRK": "Corea del Norte",
    "KOR": "Corea del Sur",
    "KWT": "Kuwait",
    "KGZ": "Kirguistán",
    "LAO": "Laos",
    "LVA": "Letonia",
    "LBN": "Líbano",
    "LSO": "Lesoto",
    "LBR": "Liberia",
    "LBY": "Libia",
    "LIE": "Liechtenstein",
    "LTU": "Lituania",
    "LUX": "Luxemburgo",
    "MDG": "Madagascar",
    "MWI": "Malaui",
    "MYS": "Malasia",
    "MDV": "Maldivas",
    "MLI": "Malí",
    "MLT": "Malta",
    "MHL": "Islas Marshall",
    "MRT": "Mauritania",
    "MUS": "Mauricio",
    "MEX": "México",
    "FSM": "Micronesia",
    "MDA": "Moldavia",
    "MCO": "Mónaco",
    "MNG": "Mongolia",
    "MNE": "Montenegro",
    "MAR": "Marruecos",
    "MOZ": "Mozambique",
    "MMR": "Birmania",
    "NAM": "Namibia",
    "NRU": "Nauru",
    "NPL": "Nepal",
    "NLD": "Países Bajos",
    "NZL": "Nueva Zelanda",
    "NIC": "Nicaragua",
    "NER": "Níger",
    "NGA": "Nigeria",
    "NOR": "Noruega",
    "OMN": "Omán",
    "PAK": "Pakistán",
    "PLW": "Palaos",
    "PAN": "Panamá",
    "PNG": "Papúa Nueva Guinea",
    "PRY": "Paraguay",
    "PER": "Perú",
    "PHL": "Filipinas",
    "POL": "Polonia",
    "PRT": "Portugal",
    "QAT": "Catar",
    "ROU": "Rumanía",
    "RUS": "Rusia",
    "RWA": "Ruanda",
    "KNA": "San Cristóbal y Nieves",
    "LCA": "Santa Lucía",
    "VCT": "San Vicente y las Granadinas",
    "WSM": "Samoa",
    "SMR": "San Marino",
    "STP": "Santo Tomé y Príncipe",
    "SAU": "Arabia Saudita",
    "SEN": "Senegal",
    "SRB": "Serbia",
    "SYC": "Seychelles",
    "SLE": "Sierra Leona",
    "SGP": "Singapur",
    "SVK": "Eslovaquia",
    "SVN": "Eslovenia",
    "SLB": "Islas Salomón",
    "SOM": "Somalia",
    "ZAF": "Sudáfrica",
    "SSD": "Sudán del Sur",
    "ESP": "España",
    "LKA": "Sri Lanka",
    "SDN": "Sudán",
    "SUR": "Surinam",
    "SWE": "Suecia",
    "CHE": "Suiza",
    "SYR": "Siria",
    "TWN": "Taiwán",
    "TJK": "Tayikistán",
    "TZA": "Tanzania",
    "THA": "Tailandia",
    "TLS": "Timor Oriental",
    "TGO": "Togo",
    "TON": "Tonga",
    "TTO": "Trinidad y Tobago",
    "TUN": "Túnez",
    "TUR": "Turquía",
    "TKM": "Turkmenistán",
    "TUV": "Tuvalu",
    "UGA": "Uganda",
    "UKR": "Ucrania",
    "ARE": "Emiratos Árabes Unidos",
    "GBR": "Reino Unido",
    "USA": "Estados Unidos",
    "URY": "Uruguay",
    "UZB": "Uzbekistán",
    "VUT": "Vanuatu",
    "VEN": "Venezuela",
    "VNM": "Vietnam",
    "YEM": "Yemen",
    "ZMB": "Zambia",
    "ZWE": "Zimbabue"
};

// Mapeo de continentes
const continentNames = {
    "Africa": "África",
    "Asia": "Asia",
    "Europe": "Europa",
    "North America": "Norteamérica",
    "South America": "Sudamérica",
    "Oceania": "Oceania",
    "Antarctica": "Antártida"
};

// Mapeo de países a continentes
const countryContinents = {
    "AFG": "Asia",
    "ALB": "Europe",
    "DZA": "Africa",
    "AND": "Europe",
    "AGO": "Africa",
    "ARG": "South America",
    "ARM": "Asia",
    "AUS": "Oceania",
    "AUT": "Europe",
    "AZE": "Asia",
    "BHS": "North America",
    "BHR": "Asia",
    "BGD": "Asia",
    "BRB": "North America",
    "BLR": "Europe",
    "BLZ": "North America",
    "BEN": "Africa",
    "BTN": "Asia",
    "BOL": "South America",
    "BIH": "Europe",
    "BWA": "Africa",
    "BVT": "Antarctica",
    "BRA": "South America",
    "BRN": "Asia",
    "BGR": "Europe",
    "BFA": "Africa",
    "BDI": "Africa",
    "KHM": "Asia",
    "CMR": "Africa",
    "CAN": "North America",
    "CPV": "Africa",
    "CYM": "North America",
    "CAF": "Africa",
    "TCD": "Africa",
    "CHL": "South America",
    "CHN": "Asia",
    "CXR": "Oceania",
    "CCK": "Oceania",
    "COL": "South America",
    "COM": "Africa",
    "COG": "Africa",
    "COD": "Africa",
    "COK": "Oceania",
    "CRI": "North America",
    "HRV": "Europe",
    "CUB": "North America",
    "CUW": "North America",
    "CYM": "North America",
    "CZE": "Europe",
    "DNK": "Europe",
    "DJI": "Africa",
    "SLB": "Oceania",
    "DMA": "North America",
    "DOM": "North America",
    "ECU": "South America",
    "EGY": "Africa",
    "SLV": "North America",
    "GNQ": "Africa",
    "ERI": "Africa",
    "EST": "Europe",
    "SWZ": "Africa",
    "ETH": "Africa",
    "FJI": "Oceania",
    "FIN": "Europe",
    "FRA": "Europe",
    "GAB": "Africa",
    "GMB": "Africa",
    "GEO": "Asia",
    "DEU": "Europe",
    "GHA": "Africa",
    "GIB": "Europe",
    "GRE": "Europe",
    "GRD": "North America",
    "GTM": "North America",
    "GIN": "Africa",
    "GUY": "South America",
    "HTI": "North America",
    "HND": "North America",
    "HKG": "Asia",
    "HUN": "Europe",
    "ISL": "Europe",
    "IND": "Asia",
    "IDN": "Asia",
    "IRL": "Europa",
    "IRN": "Asia",
    "IRQ": "Asia",
    "ISR": "Asia",
    "ITA": "Europe",
    "JAM": "North America",
    "JPN": "Asia",
    "JOR": "Asia",
    "KAZ": "Asia",
    "KEN": "Africa",
    "KIR": "Oceania",
    "KOR": "Asia",
    "KWT": "Asia",
    "KGZ": "Asia",
    "LAO": "Asia",
    "LVA": "Europe",
    "LBN": "Asia",
    "LSO": "Africa",
    "LBR": "Africa",
    "LBY": "Africa",
    "LIE": "Europe",
    "LTU": "Europe",
    "LUX": "Europe",
    "MKD": "Europe",
    "MDG": "Africa",
    "MWI": "Africa",
    "MYS": "Asia",
    "MDV": "Asia",
    "MLI": "Africa",
    "MLT": "Europe",
    "MHL": "Oceania",
    "MTQ": "North America",
    "MRT": "Africa",
    "MUS": "Africa",
    "MYT": "Africa",
    "MEX": "North America",
    "FSM": "Oceania",
    "MDA": "Europe",
    "MCO": "Europe",
    "MNG": "Asia",
    "MNE": "Europe",
    "MSR": "North America",
    "MAR": "Africa",
    "MOZ": "Africa",
    "MMR": "Asia",
    "NAM": "Africa",
    "NRU": "Oceania",
    "NPL": "Asia",
    "NLD": "Europe",
    "NZL": "Oceania",
    "NIC": "North America",
    "NER": "Africa",
    "NGA": "Africa",
    "NIU": "Oceania",
    "NFK": "Oceania",
    "PRK": "Asia",
    "MNP": "Oceania",
    "NOR": "Europe",
    "OMN": "Asia",
    "PAK": "Asia",
    "PLW": "Oceania",
    "PSE": "Asia",
    "PAN": "North America",
    "PNG": "Oceania",
    "PRY": "South America",
    "PER": "South America",
    "PHL": "Asia",
    "PCN": "Oceania",
    "POL": "Europe",
    "PRI": "North America",
    "POT": "Europe",
    "QAT": "Asia",
    "REU": "Africa",
    "ROU": "Europe",
    "RUS": "Europe",
    "RWA": "Africa",
    "SHN": "Africa",
    "KNA": "North America",
    "LCA": "North America",
    "SPM": "North America",
    "VCT": "North America",
    "WSM": "Oceania",
    "SMR": "Europe",
    "STP": "Africa",
    "SAU": "Asia",
    "SEN": "Africa",
    "SYC": "Africa",
    "SLE": "Africa",
    "SGP": "Asia",
    "SOM": "Africa",
    "ZAF": "Africa",
    "SGS": "Antarctica",
    "SSD": "Africa",
    "ESP": "Europe",
    "LKA": "Asia",
    "SDN": "Africa",
    "SUR": "South America",
    "SJM": "Europe",
    "SWZ": "Africa",
    "SYR": "Asia",
    "TJK": "Asia",
    "TZA": "Africa",
    "THA": "Asia",
    "TLS": "Asia",
    "TGO": "Africa",
    "TKL": "Oceania",
    "TON": "Oceania",
    "TUR": "Asia",
    "TKM": "Asia",
    "TUV": "Oceania",
    "UGA": "Africa",
    "UKR": "Europe",
    "ARE": "Asia",
    "GBR": "Europe",
    "USA": "North America",
    "UMI": "Oceania",
    "URY": "South America",
    "UZB": "Asia",
    "VUT": "Oceania",
    "VEN": "South America",
    "VNM": "Asia",
    "WLF": "Oceania",
    "YEM": "Asia",
    "ZMB": "Africa",
    "ZWE": "Africa"
};


// Carga el GeoJSON con los países
fetch('https://raw.githubusercontent.com/datasets/geo-boundaries-world-110m/master/countries.geojson')
    .then(response => response.json())
    .then(geojson => {
        L.vectorGrid.slicer(geojson, {
            rendererFactory: L.svg.tile,
            vectorTileLayerStyles: {
                sliced: {
                    fillColor: '#00f',
                    fillOpacity: 0.3,
                    stroke: true,
                    fill: true,
                    color: '#000',
                    weight: 1
                }
            },
            interactive: true,
            getFeatureId: f => f.properties.ISO_A3
        })
        .on('mouseover', function(e) {
            // Obtén el código ISO y usa el mapeo para obtener el nombre en español
            const isoCode = e.layer.properties.ISO_A3 || e.layer.properties.iso_a3 || e.layer.properties.ISO3;
            const countryName = countryNamesInSpanish[isoCode] || "Nombre no disponible";
            
            // Obtén el continente
            const continent = countryContinents[isoCode] || "Continente no disponible";
            const translatedContinentName = continentNames[continent] || "Continente no disponible";
            
            L.popup({ closeButton: false })
                .setLatLng(e.latlng)
                .setContent(`<div class="country-info"><strong>${countryName}</strong><br>${translatedContinentName}</div>`)
                .openOn(map);
        })
        .on('mouseout', function() {
            map.closePopup();
        })
        .addTo(map);
    });
